name = "Synixe Standardization"
author = "Synixe Contractors"
prefix = "synixe_standardization"
mainprefix = "s"

[hemtt.launch.default]
workshop = [
    "3499977893", # ADT
    "synixe:@3den_attributes_fast_load",
    "synixe:@ace_noactionmenu",
    "synixe:@ace_nocrosshair",
    "synixe:@ace_particles",
    "synixe:@ace_realisticdispersion",
    "synixe:@ace_tracers",
    "synixe:@ace",
    "synixe:@aegis_atlas",
    "synixe:@aegis_opposing_forces",
    "synixe:@aegis",
    "synixe:@cba_a3",
    "synixe:@cba_rf",
    "synixe:@cba_ws",
    "synixe:@generic_civilian_clothing",
    "synixe:@gorkas",
    "synixe:@jca_m72a7",
    "synixe:@jca_mp5a5",
    "synixe:@jca_ump45",
    "synixe:@low_visibility_attir",
    "synixe:@mu",
    "synixe:@oteden",
    "synixe:@rf",
    "synixe:@synixe_armoury",
    "synixe:@synixe_contractors",
    "synixe:@synixe_mgp",
    "synixe:@synixe_factions",
    "synixe:@theseus_services",
    "synixe:@toh_characters",
    "synixe:@ws",
]
